workflows:
  adaptive_power_engine_build:
    name: Adaptive Power Engine v4 - Build
    max_build_duration: 60
    instance_type: linux_x2
    
    environment:
      vars:
        GRADLE_OPTS: "-Xmx4096m -Dorg.gradle.daemon=false"
      java: 17
    
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
    
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
      cancel_previous_builds: true
    
    scripts:
      - name: Preparar permissões Gradle
        script: |
          chmod +x ./gradlew
      
      - name: Limpar build anterior
        script: |
          ./gradlew clean
      
      - name: Construir APK Debug
        script: |
          ./gradlew assembleDebug --stacktrace
    
    artifacts:
      - app/build/outputs/*/.apk
      - app/build/outputs/**/mapping.txt
    
    publishing:
      email:
        recipients:
          - teu_email_aqui@xxxx.com
        notify:
          success: true
          failure: true
