workflows:
  android-build:
    name: Android APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_TOOL_OPTIONS: "-Xmx3g"
    scripts:
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
